#!/bin/sh

rm -rf ~/.config/nvim
ln -sf $(pwd)/nvim ~/.config/nvim

rm -rf ~/.zshrc ~/.zprofile ~/.config/.zsh
ln -sf $(pwd)/zsh ~/.config/zsh
ln -sf $(pwd)/zsh/zshrc ~/.zshrc
ln -sf $(pwd)/zsh/zprofile ~/.zprofile
./zsh/fzf/install

rm -rf ~/.config/ranger 
ln -sf $(pwd)/ranger ~/.config/ranger

rm -rf ~/.tmux.conf
ln -sf $(pwd)/tmux.conf ~/.tmux.conf

rm -rf ~/.gitconfig
ln -sf $(pwd)/gitconfig ~/.gitconfig

rm -rf ~/.clang-format
ln -sf $(pwd)/clang-format ~/.clang-format
