set -g default-terminal "tmux-256color"
set -g terminal-overrides ",xterm-256color:Tc"
set -g default-shell /bin/zsh

set -g base-index 1
setw -g pane-base-index 1

set -sg escape-time 1

set -g status-interval 1
set -g status-keys vi
set -g status-justify left
set -g status-position bottom

set -g automatic-rename on
set -g automatic-rename-format "#{?#{==:#{pane_current_command},zsh},#{b:pane_current_path},#{pane_current_command}}"

set -g status-style fg=white,bg=default

set -g status-left "#{?client_prefix,#[bg=yellow] ,#[bg=green] }"

set -g status-right "#[fg=magenta] #S   #[fg=blue]󰌢 #H   #[fg=green] #(curl ifconfig.me)"

set -g message-style fg=white,bg=default

set -g window-status-current-format ' #I #W '
set -g window-status-format ' #I #W '
set -g window-status-style fg=black
set -g window-status-current-style fg=white

set -g renumber-windows on
