map("n", "<Leader>j", ":BufferNext<CR>", { noremap = true, silent = true })
map("n", "<Leader>k", ":BufferPrev<CR>", { noremap = true, silent = true })
map("n", "<Leader>q", ":BufferClose<CR>", { noremap = true, silent = true })
map("n", "<Leader>J", ":BufferMoveNext<CR>", { noremap = true, silent = true })
map("n", "<Leader>K", ":BufferMovePrev<CR>", { noremap = true, silent = true })
map("n", "<Leader>1", ":BufferGoto 1<CR>", { noremap = true, silent = true })
map("n", "<Leader>2", ":BufferGoto 2<CR>", { noremap = true, silent = true })
map("n", "<Leader>3", ":BufferGoto 3<CR>", { noremap = true, silent = true })
map("n", "<Leader>4", ":BufferGoto 4<CR>", { noremap = true, silent = true })
map("n", "<Leader>5", ":BufferGoto 5<CR>", { noremap = true, silent = true })
map("n", "<Leader>6", ":BufferGoto 6<CR>", { noremap = true, silent = true })
map("n", "<Leader>7", ":BufferGoto 7<CR>", { noremap = true, silent = true })
map("n", "<Leader>8", ":BufferGoto 8<CR>", { noremap = true, silent = true })
map("n", "<Leader>9", ":BufferGoto 9<CR>", { noremap = true, silent = true })
