require("nvim-tree").setup({
    disable_netrw = false,
    hijack_netrw = true,
    open_on_setup = false,
    ignore_ft_on_setup = {},
    auto_close = false,
    open_on_tab = false,
    hijack_cursor = false,
    update_cwd = true,
    update_to_buf_dir = {
        enable = false,
        auto_open = true,
    },
    diagnostics = {
        enable = true,
        icons = {
            hint = "",
            info = "",
            warning = "",
            error = "",
        },
    },
    update_focused_file = {
        enable = true,
        update_cwd = true,
        ignore_list = {},
    },
    system_open = {
        cmd = nil,
        args = {},
    },
    filters = {
        dotfiles = true,
        custom = {},
    },
    git = {
        enable = true,
        ignore = false,
        timeout = 500,
    },
    view = {
        width = 30,
        height = 30,
        hide_root_folder = false,
        side = "left",
        auto_resize = true,
        mappings = {
            custom_only = true,
            list = {
                { key = { "<CR>", "l", "o", "<2-LeftMouse>" }, action = "edit" },
                { key = { "O" }, action = "edit_no_picker" },
                { key = { "<2-RightMouse>", "L", "<C-]>" }, action = "cd" },
                { key = "<C-v>", action = "vsplit" },
                { key = "<C-x>", action = "split" },
                { key = "<C-t>", action = "tabnew" },
                { key = "<", action = "prev_sibling" },
                { key = ">", action = "next_sibling" },
                { key = "P", action = "parent_node" },
                { key = { "h", "<BS>" }, action = "close_node" },
                { key = "<C-l>", action = "preview" },
                { key = "K", action = "first_sibling" },
                { key = "J", action = "last_sibling" },
                { key = "I", action = "toggle_ignored" },
                { key = { "gh", "zh", "H" }, action = "toggle_dotfiles" },
                { key = "R", action = "refresh" },
                { key = "a", action = "create" },
                { key = "d", action = "remove" },
                { key = "D", action = "trash" },
                { key = "r", action = "rename" },
                { key = "<C-r>", action = "full_rename" },
                { key = "x", action = "cut" },
                { key = "yy", action = "copy" },
                { key = "p", action = "paste" },
                { key = "yn", action = "copy_name" },
                { key = "yp", action = "copy_path" },
                { key = "yP", action = "copy_absolute_path" },
                { key = "[c", action = "prev_git_item" },
                { key = "]c", action = "next_git_item" },
                { key = { "-", "H" }, action = "dir_up" },
                { key = "s", action = "system_open" },
                { key = "q", action = "close" },
                { key = "g?", action = "toggle_help" },
            },
        },
        number = false,
        relativenumber = false,
        signcolumn = "no",
    },
    trash = {
        cmd = "trash",
        require_confirm = true,
    },
})
vim.g.nvim_tree_quit_on_open = 0
map("n", "<Leader><Tab>", ":NvimTreeToggle<CR>", { noremap = true, silent = true })
vim.g.nvim_tree_icons = {
    default = "",
    symlink = "",
    git = {
        deleted = "",
        ignored = "◌",
        renamed = "➜",
        staged = "✓",
        unmerged = "",
        unstaged = "✗",
        untracked = "★",
    },
    folder = {
        default = "",
        empty = "",
        empty_open = "",
        open = "",
        symlink = "",
        symlink_open = "",
    },
}

vim.cmd([[hi! NvimTreeNormal guibg=#282828]])
