theme = "onedark"

[editor]
line-number = "relative"
cursorline = true
cursorcolumn = true
color-modes = true
completion-trigger-len = 1

[editor.lsp]
display-messages = true
display-inlay-hints = true


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.whitespace]
render = "all"


[editor.indent-guides]
render = true
character = "╎"
skip-levels = 1
