[class]
text_default = [
    { command = "nvim", args = [ "--" ] },
    { command = "code", args = [ "--" ], fork = true, silent = true },
]

[mimetype]
    [mimetype.text]
    inherit = "text_default"
