export FZF_DEFAULT_COMMAND="fd --type f --hidden --follow --exclude .git"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_CTRL_R_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_DEFAULT_OPTS='--bind=tab:down,shift-tab:up,ctrl-space:toggle --reverse'

export MANPAGER="nvim +Man!"
export PATH="$PATH:$HOME/.local/bin:/opt/anaconda/bin"
export VISUAL="nvim"
export EDITOR="nvim"

export TERMINAL="alacritty"
export READER="zathura"
export BROWSER="qutebrowser"

