# Q pre block. Keep at the top of this file.
[[ -f "${HOME}/Library/Application Support/amazon-q/shell/zshrc.pre.zsh" ]] && builtin source "${HOME}/Library/Application Support/amazon-q/shell/zshrc.pre.zsh"
# History
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.cache/zsh/history
setopt HIST_IGNORE_ALL_DUPS

source ~/.config/zsh/plugins/conda-zsh-completion/conda-zsh-completion.plugin.zsh
source ~/.config/zsh/plugins/fzf-tab/fzf-tab.plugin.zsh
source ~/.config/zsh/fzf-tab.zsh

source ~/.config/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh
source ~/.config/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh

source ~/.config/zsh/plugins/zsh-z/zsh-z.plugin.zsh
source ~/.config/zsh/plugins/zsh-autopair/autopair.zsh
source ~/.config/zsh/plugins/zsh-brew/zsh-brew.plugin.zsh
source ~/.config/zsh/plugins/zsh-extract/extract.plugin.zsh

source ~/.config/zsh/vi.zsh
source ~/.config/zsh/alias.zsh
source ~/.config/zsh/prompt.zsh
source ~/.config/zsh/bindkey.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export LANG="zh_CN.UTF-8"
conda config --set changeps1 false
