HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.cache/zsh_history
setopt HIST_IGNORE_ALL_DUPS

export LANG="zh_CN.UTF-8"

source ~/.config/zsh/plugins/conda-zsh-completion/conda-zsh-completion.plugin.zsh
source ~/.config/zsh/plugins/fzf-tab/fzf-tab.plugin.zsh
source ~/.config/zsh/fzf-tab.zsh

source ~/.config/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh
source ~/.config/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh
source ~/.config/zsh/plugins/zsh-autopair/autopair.zsh
source ~/.config/zsh/plugins/zsh-z/zsh-z.plugin.zsh

source ~/.config/zsh/plugins/zsh-autovenv/zsh-autovenv.plugin.zsh

if [[ "$(uname)" == "Darwin" ]]; then
    source ~/.config/zsh/plugins/zsh-brew/zsh-brew.plugin.zsh
fi

source ~/.config/zsh/vi.zsh
source ~/.config/zsh/alias.zsh
source ~/.config/zsh/prompt.zsh
source ~/.config/zsh/bindkey.zsh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

autoload -Uz compinit && compinit -i
eval "$(uv generate-shell-completion zsh)"


if command -v direnv >/dev/null 2>&1; then
    DIRENV_LOG_FORMAT=
    eval "$(direnv hook zsh)"

    # ensure compatibility tmux <-> direnv
    if [ -n "$TMUX" ] && [ -n "$DIRENV_DIR" ]; then
        direnv reload > /dev/null 2>&1
    fi
fi


